---
title: "gk_frequency_of_opened_issues"
author: "Ben Rombaut"
date: "11/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("gk_load_data.R")
```

## RQ1: Types of updates (major, minor, patch) that break a client's build
Of 79,079 GKIs:
- Major: 122
- Minor: 27226
- Patch: 51731

### Plot frequency of types of breaking updates
```{r}
freqs <- table(gki_with_dependency$update_type)
## Make the freqs numbers (rather than factors)
freqs <- as.numeric(as.character(freqs))
## Find a range of y's that'll leave sufficient space above the tallest bar
ylim <- c(0, 1.1*max(freqs))
## Plot and store
# png("plots/breaking_update_type_counts.png")
bp <- barplot(
  height=freqs,
  ylim=ylim,
  col=rgb(0.8, 0.1, 0.1, 0.5),
  xlab="Update Type",
  names.arg=c("major", "minor", "patch"), 
  ylab="Count",
  main="Counts of Breaking Update Types"
)
text(x=bp, y=freqs, label=freqs, pos=3, cex=0.8, col="red")
# dev.off()
```

### What packages cause the most breakages?
```{r}
ghi_with_dependency_name = gki[!(issue_dependency_name %in% null_values)]
packages_count = data.table(as.data.frame(table(ghi_with_dependency_name$issue_dependency_name)))
first_ten = head(packages_count[order(-Freq)], 10)
ylim <- c(0, 1.1*max(first_ten$Freq))
# png("plots/most_frequent_breaking_provider_packages.png")
bp <- barplot(
  first_ten$Freq,
  ylim=ylim,
  col=rgb(0.0, 0.2, 0.8, 0.5),
  names.arg=first_ten$Var1, 
  horiz=FALSE, 
  cex.names=0.8, 
  main="Most Frequent Breaking Packages",
  ylab="Times Package Broke a Client's Build",
  las=2
)
text(x=bp, y=first_ten$Freq, label=first_ten$Freq, pos=3, cex=0.7, col=rgb(0.0, 0.1, 0.9, 0.9))
# dev.off()
```


### How many issues per day/week/month are opened by the bot?
#### Day of Week
```{r}
gki.created_at <- gki[,'issue_created_at']

gki.created_at %>% 
  group_by(day_of_week=as.POSIXlt(issue_created_at)$wday) %>% 
  tally() ->
  day_of_week_issues

# png("plots/breaking_updates_day_of_week.png")
barplot(height=day_of_week_issues$n,
  main="Day of Week Issues Opened by Greeneeper",
  xlab="",
  ylab="Issues",
  col="lightgreen",
  names.arg=c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"),
  cex.names=0.8,
  las=1
)
# dev.off()
```

#### Day of Month
```{r}
gki.created_at %>% 
  group_by(day_of_month=as.POSIXlt(issue_created_at)$mday) %>% 
  tally() ->
  day_of_month_issues

# png("plots/breaking_updates_day_of_month.png")
barplot(height=day_of_month_issues$n,
  main="Day of Month Issues Opened by Greeneeper",
  xlab="",
  ylab="Issues",
  col="forestgreen",
  names.arg=seq(1, 31),
  cex.names=0.8,
  las=1
)
# dev.off()
```

#### Week
```{r}
gki.created_at %>% 
  group_by(week=floor_date(issue_created_at, "week")) %>% 
  tally() ->
  weekly_issues

# png("plots/breaking_updates_opened_per_week.png")
barplot(height=weekly_issues$n,
  main="Weekly Issues Opened by Greeneeper",
  xlab="",
  ylab="Issues",
  col="deepskyblue",
  names.arg=weekly_issues$week,
  cex.names=0.9,
  las=1
)
# dev.off()

```

#### Month
```{r}
gki.created_at %>% 
  group_by(month=format(floor_date(issue_created_at, "month"), "%Y-%m")) %>% 
  tally() ->
  monthly_issues

# png("plots/breaking_updates_opened_per_month.png")
barplot(height=monthly_issues$n,
  main="Monthly Issues Opened by Greeneeper",
  xlab="",
  ylab="Issues",
  col="darkmagenta",
  names.arg=monthly_issues$month,
  cex.names=0.9,
  las=2
)
# dev.off()
```

#### Year
```{r}
gki.created_at %>% 
  group_by(year=floor_date(issue_created_at, "year")) %>% 
  tally() ->
  yearly_issues

```
